### ISSUE TITLE
Union of 2 overlapping paths returns an empty path

### ISSUE THREAD

**Issue by ghenania** [hfutrell/BezierKit#63]
Let consider the 2 following UIBezierPath:
```
let p1 = UIBezierPath()
p1.move(to: CGPoint(x: 160.30770651563628, y: 827.7553004653367))
p1.addCurve(to: CGPoint(x: 110.26942663248718, y: 568.5268524837642), controlPoint1: CGPoint(x: 181.33161356383755, y: 737.7466984152248), controlPoint2: CGPoint(x: 164.05060972624904, y: 653.3356412085424))
p1.addCurve(to: CGPoint(x: 68.86790851824688, y: 559.2578558910238), controlPoint1: CGPoint(x: 101.39627582752009, y: 554.534576214393), controlPoint2: CGPoint(x: 82.86018478761805, y: 550.3847050860568))
p1.addCurve(to: CGPoint(x: 59.59891192550654, y: 600.6593740052641), controlPoint1: CGPoint(x: 54.875632248875704, y: 568.1310066959909), controlPoint2: CGPoint(x: 50.725761120539445, y: 586.667097735893))
p1.addCurve(to: CGPoint(x: 101.88038125865839, y: 814.1080420111522), controlPoint1: CGPoint(x: 105.11513351206828, y: 672.4349541994575), controlPoint2: CGPoint(x: 119.06082214735332, y: 740.5542794564268))
p1.addCurve(to: CGPoint(x: 124.27041466005505, y: 850.1453338667334), controlPoint1: CGPoint(x: 98.11179489803564, y: 830.2423023675684), controlPoint2: CGPoint(x: 108.13615430363883, y: 846.3767475061106))
p1.addCurve(to: CGPoint(x: 160.30770651563628, y: 827.7553004653367), controlPoint1: CGPoint(x: 140.40467501647126, y: 853.9139202273561), controlPoint2: CGPoint(x: 156.53912015501353, y: 843.889560821753))
```
and 

```
let p2 = UIBezierPath()
p2.move(to: CGPoint(x: 110.01560660410875, y: 568.1334199999095))
p2.addCurve(to: CGPoint(x: -34.46691786355873, y: 426.72807843882487), controlPoint1: CGPoint(x: 64.94829801467844, y: 499.45942595887277), controlPoint2: CGPoint(x: 20.78869552632778, y: 454.67344613026177))
p2.addCurve(to: CGPoint(x: -69.07061390857123, y: 474.860094579322), controlPoint1: CGPoint(x: -65.01464367993249, y: 411.2786538880151), controlPoint2: CGPoint(x: -93.44515961076199, y: 450.82408423410607))
p2.addLine(to: CGPoint(x: 63.869824962902115, y: 605.9541384664693))
p2.addCurve(to: CGPoint(x: 110.01560660410875, y: 568.1334199999095), controlPoint1: CGPoint(x: 89.4862743247028, y: 631.2148038093562), controlPoint2: CGPoint(x: 129.75430800678396, y: 598.2114411849384))
```

If we create 2 Paths and perform a union,
```
let path1 = Path(cgPath: p1.cgPath)
let path2 = Path(cgPath: p2.cgPath)
let final = path1.union(path2)
```

 the `final` Path is Empty while the 2 Paths are overlapping.

**Comment by hfutrell** [comment]
hi @ghenania. I appreciate the detailed reproduction steps!

For many methods such as `union` `BezierKit` uses an accuracy parameter which default value is `0.5` (which represents about a pixel if the points are in view coordinates). It looks like the default accuracy may not be sufficient in your case. 

When I tried `let final = path1.union(path2, accuracy: 0.1)` this made resulting union non-empty for me. Does this work for you?

I am working to provide higher default accuracy in BezierKit, but for the intersection routines there is a trade-off between speed and accuracy. I am trying to improve these routines by using the Bezier Clipping algorithm.

**Comment by ghenania** [comment]
Hey @hfutrell,

Thanks for your quick answer. 
Indeed I suspected that was an accuracy issue so I retried with  all points rounded to integers and it works perfectly. I think it's good enough for me but thanks I know now that if I need more precision, I just have to adjust accuracy to 0.1 ;)

By the way, I have another question: Is there a quick and clean way to merge (Union) all Path components, other that iterating on them with `union` ?

**Comment by hfutrell** [comment]
@ghenania I'm glad increasing the accuracy works for you!

I would union all the path components individually, as you said. Something like  `let result = path.components.reduce(Path(), $0.union($1))`

**Comment by ghenania** [comment]
Thanks @hfutrell `path.crossingsRemoved()` perfectly fits my needs!
Thanks again for your amazing work.
