### ISSUE TITLE
how to quiet the SwiftLint warning?

### ISSUE THREAD

**Issue by mbutterick** [hfutrell/BezierKit#82]
<img width="318" alt="Screen Shot 2021-01-20 at Jan 20  3 35 09 PM" src="https://user-images.githubusercontent.com/1425051/105253840-2362bd80-5b35-11eb-8d2f-9b17149a2dfd.png">

Since I upgraded to the current version of `BezierKit` I’m getting this warning. I installed `SwiftLint` as a package and added it to the `BezierKit` target as shown below, but the warning persists.

What else is to be done?

<img width="735" alt="Screen Shot 2021-01-20 at Jan 20  3 36 01 PM" src="https://user-images.githubusercontent.com/1425051/105253922-50af6b80-5b35-11eb-9b09-7717ff4216e5.png">

**Comment by hfutrell** [comment]
@mbutterick I'm not sure SwiftLint can work being installed this way.

I would install SwiftLint following their "Homebrew" directions here:
https://github.com/realm/SwiftLint

Or you can go here and download the `SwiftLint.pgk` installer and use that (haven't tried this route, but avoids having to use command line, I think).
https://github.com/realm/SwiftLint/releases/tag/0.42.0

Let me know if either of those options works.

**Comment by mbutterick** [comment]
Thanks for the pointers. I can sort it out based on that.
